# Generated by Django 3.1.5 on 2021-01-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='line_id',
            new_name='line_channel_id',
        ),
    ]
