# Generated by Django 3.1.5 on 2021-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20210121_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='zipcode',
            field=models.CharField(default='000', max_length=10),
        ),
    ]
