# Generated by Django 3.1.5 on 2021-01-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20210116_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar',
        ),
    ]
