# Generated by Django 3.1.5 on 2021-01-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_customermodel_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='city',
            new_name='county',
        ),
    ]
